######################################################################
# Automatically generated by qmake (2.01a) Tue May 21 17:23:53 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += IconEditor.h   MainWindow.h
SOURCES += IconEditor.cpp MainWindow.cpp main.cpp
