######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 5 17:27:35 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += QuitButton.cpp
