######################################################################
# Automatically generated by qmake (2.01a) Wed May 8 16:11:46 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FindDialog.h
SOURCES += FindDialog.cpp Main.cpp
