######################################################################
# Automatically generated by qmake (3.0) sex nov 6 10:04:12 2015
######################################################################

TEMPLATE = app
TARGET = colorselect
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += ColorSelect.h ui_ColorSelect.h
FORMS += ColorSelect.ui
SOURCES += ColorSelect.cpp main.cpp
