######################################################################
# Automatically generated by qmake (2.01a) Tue May 21 15:26:55 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Buto.h
SOURCES += Buto.cpp main.cpp
