######################################################################
# Automatically generated by qmake (2.01a) Wed May 8 18:29:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui

HEADERS += GoToCellDialog.h

SOURCES += main.cpp
SOURCES += GoToCellDialog.cpp
