######################################################################
# Automatically generated by qmake (3.0) qui nov 5 16:35:28 2015
######################################################################

TEMPLATE = app
TARGET = ageapp
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += AgeApp.cpp
