######################################################################
# Automatically generated by qmake (2.01a) qui 14. nov 09:48:13 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textrender.h
SOURCES += main.cpp textrender.cpp
