######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 4 19:03:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += HelloQt.cpp
